version : '3'

services:
    lb:
        image: haproxy
        ports:
            - 8080:8080
        volumes:
            - ./haproxy:/usr/local/etc/haproxy

    cqrs-event-sourcing-1:
        image: cqrs-event-sourcing
        ports:
          - 3101:3101
        environment:
            - APPID=instance-1
            - PORT=3101
            - DOCKER_HOST=host.docker.internal

    cqrs-event-sourcing-2:
        image: cqrs-event-sourcing
        ports:
          - 3102:3102
        environment:
            - APPID=instance-2
            - PORT=3102
            - DOCKER_HOST=host.docker.internal

    cqrs-event-sourcing-3:
        image: cqrs-event-sourcing
        ports:
            - 3103:3103
        environment:
            - APPID=instance-3
            - PORT=3103
            - DOCKER_HOST=host.docker.internal

